rewards:
  coins:
    kill: 5
    final-kill: 15
    bed-break: 20
    win: 50
    loss: 5

  xp:
    kill: 10
    final-kill: 30
    bed-break: 40
    win: 100
    loss: 10

database:
  host: localhost
  port: 3306
  name: glimzo
  user: root
  password: ""
