name: GlimzoBedWars
version: 1.0.0
main: me.pikashrey.glimzobedwars.GlimzoBedWars
api-version: 1.8
authors: [pikashrey]
description: BedWars bridge plugin for Glimzo Network

depend:
  - GlimzoCore
  - BedWars1058
